name: New Release
on:
  push:
    branches:
      - setup-release-workflow
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Clone client
        uses: actions/checkout@master
        with:
          repository: swing-opensource/swingmusic-client
          ref: refs/heads/master
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install yarn
        run: |
          npm install -g yarn
      - name: Install dependencies
        run: |
          yarn install
      - name: Build client
        run: |
          yarn build
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.13"
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Checkout server
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Copy client build
        run: |
          cp -r ../swingmusic-client/dist ./client
      - name: Build server
        run: |
          python -m poetry run python manage.py --build
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      - name: Print CWD
        run: |
          pwd
          ls -la
      - name: Verify build
        run: |
          if [ ! -f "dist/swingmusic" ]; then
            echo "Build failed"
            exit 1
          fi
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/swingmusic"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          commit: ${{ github.sha }}
          draft: true
          artifactErrorsFailBuild: true
          name: New Release
